/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AthleteRegistration } from "./AthleteRegistration";
export type { SimpleTest } from "./SimpleTest";
export type { TestArtifact } from "./TestArtifact";
