/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  SepoliaConfig,
  SepoliaConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/SepoliaConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "protocolId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052346101c057600060606100156101c5565b8281528260208201528260408201520152731364cbbf2cdf5032c47d8226a6f6fbd2afcdacac60606100456101c5565b7350157cffd6bbfa2dece204a89ec419c23ef5755d815273cd3ab3bd6bcc0c0bf3e27912a92043e817b1cf69602082015273a02cda4ca3a71d7c46997716f4283aa851c28812604082015201527350157cffd6bbfa2dece204a89ec419c23ef5755d60018060a01b03197f9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497005416177f9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497005573cd3ab3bd6bcc0c0bf3e27912a92043e817b1cf6960018060a01b03196000805160206102958339815191525416176000805160206102958339815191525573a02cda4ca3a71d7c46997716f4283aa851c2881260018060a01b03196000805160206102b58339815191525416176000805160206102b583398151915255731364cbbf2cdf5032c47d8226a6f6fbd2afcdacac60018060a01b031960008051602061027583398151915254161760008051602061027583398151915255604051607a90816101fb8239f35b600080fd5b60405190608082016001600160401b038111838210176101e457604052565b634e487b7160e01b600052604160045260246000fdfe6080806040526004361015601257600080fd5b60003560e01c63da1f12ab14602657600080fd5b34603f576000366003190112603f578061271160209252f35b600080fdfea2646970667358221220abb50c80743aa641f868dcf6549a4f3b44ebdc095e383c3bd7f5dfe2b1b8fdaa64736f6c634300081b00339e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497039e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497019e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e4649702";

type SepoliaConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SepoliaConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SepoliaConfig__factory extends ContractFactory {
  constructor(...args: SepoliaConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SepoliaConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SepoliaConfig__factory {
    return super.connect(runner) as SepoliaConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SepoliaConfigInterface {
    return new Interface(_abi) as SepoliaConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SepoliaConfig {
    return new Contract(address, _abi, runner) as unknown as SepoliaConfig;
  }
}
