/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AthleteRegistration__factory } from "./AthleteRegistration__factory";
export { SimpleTest__factory } from "./SimpleTest__factory";
export { TestArtifact__factory } from "./TestArtifact__factory";
