/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  TestArtifact,
  TestArtifactInterface,
} from "../../contracts/TestArtifact";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "setValue",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "value",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234601857607b600055609d9081601e8239f35b600080fdfe6080806040526004361015601257600080fd5b60003560e01c9081633fa4f24514604e5750635524107714603257600080fd5b346049576020366003190112604957600435600055005b600080fd5b3460495760003660031901126049576020906000548152f3fea2646970667358221220988c00fe1ff1079d1d3bc5a9b28310b05e69689ae1f1ce32e7a9ebf0835a494164736f6c634300081b0033";

type TestArtifactConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TestArtifactConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TestArtifact__factory extends ContractFactory {
  constructor(...args: TestArtifactConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TestArtifact & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TestArtifact__factory {
    return super.connect(runner) as TestArtifact__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TestArtifactInterface {
    return new Interface(_abi) as TestArtifactInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TestArtifact {
    return new Contract(address, _abi, runner) as unknown as TestArtifact;
  }
}
