/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AthleteRegistrationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "categoryMinAges"
      | "checkAgeRequirement"
      | "getAllEncryptedAthleteInfo"
      | "getAthleteAtIndex"
      | "getEncryptedAge"
      | "getEncryptedCategory"
      | "getEncryptedContact"
      | "getEncryptedName"
      | "getRegistrationTimestamp"
      | "getTotalAthletes"
      | "isAthleteRegistered"
      | "protocolId"
      | "registerAthlete"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AthleteInfoUpdated" | "AthleteRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "categoryMinAges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAgeRequirement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEncryptedAthleteInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAthleteAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedCategory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedContact",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRegistrationTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAthletes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAthleteRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerAthlete",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "categoryMinAges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAgeRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEncryptedAthleteInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAthleteAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedContact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegistrationTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAthletes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAthleteRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAthlete",
    data: BytesLike
  ): Result;
}

export namespace AthleteInfoUpdatedEvent {
  export type InputTuple = [athlete: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [athlete: string, timestamp: bigint];
  export interface OutputObject {
    athlete: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AthleteRegisteredEvent {
  export type InputTuple = [athlete: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [athlete: string, timestamp: bigint];
  export interface OutputObject {
    athlete: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AthleteRegistration extends BaseContract {
  connect(runner?: ContractRunner | null): AthleteRegistration;
  waitForDeployment(): Promise<this>;

  interface: AthleteRegistrationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  categoryMinAges: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  checkAgeRequirement: TypedContractMethod<[], [string], "nonpayable">;

  getAllEncryptedAthleteInfo: TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint] & {
        encryptedName: string;
        encryptedAge: string;
        encryptedContact: string;
        encryptedCategory: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getAthleteAtIndex: TypedContractMethod<
    [index: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedAge: TypedContractMethod<[], [string], "view">;

  getEncryptedCategory: TypedContractMethod<[], [string], "view">;

  getEncryptedContact: TypedContractMethod<[], [string], "view">;

  getEncryptedName: TypedContractMethod<[], [string], "view">;

  getRegistrationTimestamp: TypedContractMethod<[], [bigint], "view">;

  getTotalAthletes: TypedContractMethod<[], [bigint], "view">;

  isAthleteRegistered: TypedContractMethod<[], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  registerAthlete: TypedContractMethod<
    [
      _encryptedName: BytesLike,
      _nameProof: BytesLike,
      _encryptedAge: BytesLike,
      _ageProof: BytesLike,
      _encryptedContact: BytesLike,
      _contactProof: BytesLike,
      _encryptedCategory: BytesLike,
      _categoryProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "categoryMinAges"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkAgeRequirement"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllEncryptedAthleteInfo"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, string, bigint] & {
        encryptedName: string;
        encryptedAge: string;
        encryptedContact: string;
        encryptedCategory: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAthleteAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedAge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedCategory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedContact"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedName"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRegistrationTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalAthletes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAthleteRegistered"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerAthlete"
  ): TypedContractMethod<
    [
      _encryptedName: BytesLike,
      _nameProof: BytesLike,
      _encryptedAge: BytesLike,
      _ageProof: BytesLike,
      _encryptedContact: BytesLike,
      _contactProof: BytesLike,
      _encryptedCategory: BytesLike,
      _categoryProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AthleteInfoUpdated"
  ): TypedContractEvent<
    AthleteInfoUpdatedEvent.InputTuple,
    AthleteInfoUpdatedEvent.OutputTuple,
    AthleteInfoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AthleteRegistered"
  ): TypedContractEvent<
    AthleteRegisteredEvent.InputTuple,
    AthleteRegisteredEvent.OutputTuple,
    AthleteRegisteredEvent.OutputObject
  >;

  filters: {
    "AthleteInfoUpdated(address,uint256)": TypedContractEvent<
      AthleteInfoUpdatedEvent.InputTuple,
      AthleteInfoUpdatedEvent.OutputTuple,
      AthleteInfoUpdatedEvent.OutputObject
    >;
    AthleteInfoUpdated: TypedContractEvent<
      AthleteInfoUpdatedEvent.InputTuple,
      AthleteInfoUpdatedEvent.OutputTuple,
      AthleteInfoUpdatedEvent.OutputObject
    >;

    "AthleteRegistered(address,uint256)": TypedContractEvent<
      AthleteRegisteredEvent.InputTuple,
      AthleteRegisteredEvent.OutputTuple,
      AthleteRegisteredEvent.OutputObject
    >;
    AthleteRegistered: TypedContractEvent<
      AthleteRegisteredEvent.InputTuple,
      AthleteRegisteredEvent.OutputTuple,
      AthleteRegisteredEvent.OutputObject
    >;
  };
}
